version: '3.8'

services:
  backend:
    build: ./backend
    container_name: societra-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-misty-silence-a16mvhbt-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      SPRING_DATASOURCE_USERNAME: "neondb_owner"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_DATABASE: "postgresql"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    container_name: societra-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
