version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: societra-db
    environment:
      POSTGRES_DB: chs_society
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: societra-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/chs_society"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_DATABASE: "postgresql"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: societra-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
