# Production profile with Postgres in Docker
spring.datasource.url=jdbc:postgresql://${DB_HOST:ep-misty-silence-a16mvhbt-pooler.ap-southeast-1.aws.neon.tech}/${POSTGRES_DB:neondb}?sslmode=require
spring.datasource.username=${POSTGRES_USER:neondb_owner}
spring.datasource.password=${POSTGRES_PASSWORD:npg_PKx3XGJ5tpeD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
