package com.chs.society.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;
    private final com.chs.society.config.props.MailProperties mailProperties;

    @Async
    public void sendSimpleEmail(String to, String subject, String body) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");
            helper.setFrom(mailProperties.getFrom());
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(body, false);
            mailSender.send(message);
            log.info("Email sent to {} | Subject: {}", to, subject);
        } catch (Exception e) {
            log.error("Failed to send email to {}: {}", to, e.getMessage());
        }
    }

    @Async
    public void sendEmailWithPdfAttachment(String to, String subject, String body,
            byte[] pdfBytes, String fileName) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setFrom(mailProperties.getFrom());
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(body, false);

            // Attach PDF
            helper.addAttachment(fileName, new org.springframework.core.io.ByteArrayResource(pdfBytes),
                    "application/pdf");

            mailSender.send(message);
            log.info("Email with PDF attachment sent to {} | File: {}", to, fileName);
        } catch (MessagingException e) {
            log.error("Failed to send email with attachment to {}: {}", to, e.getMessage());
        }
    }

    @Async
    public void sendBillEmail(String to, String memberName, String billNumber,
            String amount, String dueDate, String societyName,
            byte[] pdfBytes) {
        String subject = "SOCIETRA: Maintenance Bill " + billNumber + " - " + societyName;
        String body = String.format(
                "Dear %s,\n\n" +
                        "Your maintenance bill has been generated by %s.\n\n" +
                        "  Bill No    : %s\n" +
                        "  Amount     : ₹%s\n" +
                        "  Due Date   : %s\n\n" +
                        "Please find your bill attached. Kindly pay before the due date to avoid interest charges.\n\n"
                        +
                        "You can also pay online via the SOCIETRA Member Portal.\n\n" +
                        "Regards,\n%s Management",
                memberName, societyName, billNumber, amount, dueDate, societyName);

        sendEmailWithPdfAttachment(to, subject, body, pdfBytes, "Bill_" + billNumber + ".pdf");
    }

    @Async
    public void sendReceiptEmail(String to, String memberName, String receiptNumber,
            String amount, String currentBalance, String societyName,
            byte[] pdfBytes) {
        String subject = "SOCIETRA: Payment Confirmation - Receipt " + receiptNumber;
        String body = String.format(
                "Dear %s,\n\n" +
                        "Thank you for your payment to %s.\n\n" +
                        "  Receipt No       : %s\n" +
                        "  Amount Paid      : ₹%s\n" +
                        "  Current Balance  : ₹%s\n\n" +
                        "Your official receipt is attached for your records.\n\n" +
                        "Regards,\n%s Management",
                memberName, societyName, receiptNumber, amount, currentBalance, societyName);

        sendEmailWithPdfAttachment(to, subject, body, pdfBytes, "Receipt_" + receiptNumber + ".pdf");
    }

    @Async
    public void sendMeetingInviteEmail(String to, String memberName,
            String meetingTitle, String meetingType,
            String dateStr, String venue, String agenda,
            String societyName, String adminName, String adminEmail) {
        String subject = societyName + ": Meeting Notice – " + meetingTitle;
        String agendaLine = (agenda != null && !agenda.isBlank()) ? "  Agenda    : " + agenda + "\n" : "";
        String body = String.format(
                "Dear %s,\n\n" +
                        "You are cordially invited to attend the following meeting organised by %s:\n\n" +
                        "  Meeting   : %s (%s)\n" +
                        "  Date/Time : %s\n" +
                        "  Venue     : %s\n" +
                        "%s" +
                        "\nPlease confirm your attendance via the SOCIETRA Member Portal (RSVP).\n\n" +
                        "For queries, contact the society admin:\n" +
                        "  Name  : %s\n" +
                        "  Email : %s\n\n" +
                        "Regards,\n%s Management",
                memberName, societyName,
                meetingTitle, meetingType, dateStr, venue, agendaLine,
                adminName, adminEmail != null ? adminEmail : "N/A",
                societyName);

        sendSimpleEmail(to, subject, body);
    }
}
